// This is a generated file. The source files are in react-dom-bindings/src/server/fizz-instruction-set.
// The build script is at scripts/rollup/generate-inline-fizz-runtime.js.
// Run `yarn generate-inline-fizz-runtime` to generate.
export const markShellTime =
  'requestAnimationFrame(function(){$RT=performance.now()});';
export const clientRenderBoundary =
  '$RX=function(d,e,f,g,h){var c,b=document.getElementById(d);if(!b)a:{b=document;for(b=b.createTreeWalker(b.documentElement||b,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);c=b.nextNode();)if(7===c.nodeType){var a;if(a="start"===c.target)a=c,a="function"===typeof a.getAttribute?a.getAttribute("name"):(a=(a.data||a.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?a[1]:null,a=a===d;if(a){b=c;break a}}else{if(a=8===c.nodeType)a=c.data,"string"!==typeof a||63!==a.charCodeAt(0)?a=!1:(a=a.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),a=null!=a&&"start"===a[1]&&a[2]===d);if(a){b=c;break a}}b=null}if(c=b)b=c.previousSibling,b.data="$!",a=c,1!==c.nodeType&&(a=b.ownerDocument.createElement("template"),a.id=d,b.parentNode.insertBefore(a,c)),d=a.dataset,null!=e&&(d.dgst=e),f&&(d.msg=f),g&&(d.stck=g),h&&(d.cstck=h),b._reactRetry&&b._reactRetry()};';
export const completeBoundary =
  'function k(d){var c=document;c=c.createTreeWalker(c.documentElement||c,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);for(var a;a=c.nextNode();)if(7===a.nodeType){var b;if(b="start"===a.target)b=a,b="function"===typeof b.getAttribute?b.getAttribute("name"):(b=(b.data||b.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?b[1]:null,b=b===d;if(b)return a}else{if(b=8===a.nodeType)b=a.data,"string"!==typeof b||63!==b.charCodeAt(0)?b=!1:(b=b.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),b=null!=b&&"start"===b[1]&&b[2]===d);if(b)return a}return null};$RB=[];\n$RV=function(d){$RT=performance.now();for(var c=0;c<d.length;c+=2){var a=d[c],b=d[c+1];null!==b.parentNode&&b.parentNode.removeChild(b);var e=a.parentNode;if(e){var g=a.previousSibling,h=0;do{if(a&&8===a.nodeType){var f=a.data;if("/$"===f||"/&"===f)if(0===h)break;else h--;else("$"===f||36===f.charCodeAt(0)&&63===f.charCodeAt(1)||"$~"===f||"$!"===f||"&"===f)&&h++}f=a.nextSibling;e.removeChild(a);a=f}while(a);for(;b.firstChild;)e.insertBefore(b.firstChild,a);g.data="$";g._reactRetry&&requestAnimationFrame(g._reactRetry)}}d.length=\n0};\n$RC=function(d,c){if(null==c){a:{c=document.querySelectorAll("template");for(var a=0;a<c.length;a++)if(c[a].getAttribute("for")===d){c=c[a];break a}c=null}if(null!==c&&null!==c.parentNode)if(a=k(d),null===a||null===a.parentNode)c.parentNode.removeChild(c);else{for(var b=a.parentNode,e=a.nextSibling;e;){var g=e.nextSibling,h=7===e.nodeType?"end"===e.target:8===e.nodeType?"string"===typeof e.data&&/^\\?end\\b/.test(e.data):!1;b.removeChild(e);if(h)break;e=g}for(e=c.content;e.firstChild;)b.insertBefore(e.firstChild,a);\nb.removeChild(a);null!==c.parentNode&&c.parentNode.removeChild(c)}d="$?"+d.slice(d.indexOf(":")+1);for(c=document.createTreeWalker(document.documentElement||document,128);a=c.nextNode();)if(a.data===d){d=a;d.data="$";d._reactRetry&&requestAnimationFrame(d._reactRetry);break}}else if(c=document.getElementById(c))(d=(a=document.getElementById(d))?a:k(d))?(d.previousSibling.data="$~",$RB.push(d,c),2===$RB.length&&("number"!==typeof $RT?requestAnimationFrame($RV.bind(null,\n$RB)):(d=performance.now(),setTimeout($RV.bind(null,$RB),2300>d&&2E3<d?2300-d:$RT+300-d)))):c.parentNode.removeChild(c)};';
export const completeBoundaryUpgradeToViewTransitions =
  '$RV=function(B,g){function h(a,c){var e=a.getAttribute(c);e&&(c=a.style,m.push(a,c.viewTransitionName,c.viewTransitionClass),"auto"!==e&&(c.viewTransitionClass=e),(a=a.getAttribute("vt-name"))||(a="_T_"+N++ +"_"),a=CSS.escape(a)!==a?"r-"+btoa(a).replace(/=/g,""):a,c.viewTransitionName=a,C=!0)}var C=!1,N=0,m=[];try{var f=document.__reactViewTransition;if(f){f.finished.finally($RV.bind(null,g));return}var n=new Map;for(f=1;f<g.length;f+=2)for(var k=g[f].querySelectorAll("[vt-share]"),d=0;d<k.length;d++){var b=k[d];n.set(b.getAttribute("vt-name"),b)}var u=[];for(k=0;k<g.length;k+=2){var D=g[k],x=D.parentNode;if(x){var v=x.getBoundingClientRect();if(v.left||v.top||v.width||v.height){b=D;for(f=0;b;){if(8===b.nodeType){var l=b.data;if("/$"===l)if(0===f)break;else f--;else("$"===l||36===l.charCodeAt(0)&&63===l.charCodeAt(1)||"$~"===l||"$!"===l||"&"===l)&&f++}else if(1===b.nodeType){d=b;var E=d.getAttribute("vt-name"),y=n.get(E);h(d,y?"vt-share":"vt-exit");y&&(h(y,"vt-share"),n.set(E,\nnull));for(var F=d.querySelectorAll("[vt-share]"),z=0;z<F.length;z++){var G=F[z],H=G.getAttribute("vt-name"),I=n.get(H);I&&(h(G,"vt-share"),h(I,"vt-share"),n.set(H,null))}var J=d.querySelectorAll("[vt-parent-exit]");for(d=0;d<J.length;d++)h(J[d],"vt-parent-exit")}b=b.nextSibling}for(var K=g[k+1],p=K.firstElementChild;p;){null!==n.get(p.getAttribute("vt-name"))&&h(p,"vt-enter");var L=p.querySelectorAll("[vt-parent-enter]");for(b=0;b<L.length;b++)h(L[b],"vt-parent-enter");p=p.nextElementSibling}b=x;\ndo for(var q=b.firstElementChild;q;){var M=q.getAttribute("vt-update");M&&"none"!==M&&!m.includes(q)&&h(q,"vt-update");q=q.nextElementSibling}while((b=b.parentNode)&&1===b.nodeType&&"none"!==b.getAttribute("vt-update"));u.push.apply(u,K.querySelectorAll(\'img[src]:not([loading="lazy"])\'))}}}if(C){var A=document.__reactViewTransition=document.startViewTransition({update:function(){B(g);for(var a=[document.documentElement.clientHeight,document.fonts.ready],c={},e=0;e<u.length;c={g:c.g},e++)if(c.g=u[e],\n!c.g.complete){var r=c.g.getBoundingClientRect();0<r.bottom&&0<r.right&&r.top<window.innerHeight&&r.left<window.innerWidth&&(r=new Promise(function(w){return function(t){w.g.addEventListener("load",t);w.g.addEventListener("error",t)}}(c)),a.push(r))}return Promise.race([Promise.all(a),new Promise(function(w){var t=performance.now();setTimeout(w,2300>t&&2E3<t?2300-t:500)})])},types:[]});A.ready.finally(function(){for(var a=m.length-3;0<=a;a-=3){var c=m[a],e=c.style;e.viewTransitionName=m[a+1];e.viewTransitionClass=\nm[a+1];""===c.getAttribute("style")&&c.removeAttribute("style")}});A.finished.finally(function(){document.__reactViewTransition===A&&(document.__reactViewTransition=null)});$RB=[];return}}catch(a){}B(g)}.bind(null,$RV);';
export const completeBoundaryWithStyles =
  'function x(c){var f=document.getElementById(c);if(f)c=f;else a:{f=document;f=f.createTreeWalker(f.documentElement||f,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);for(var d;d=f.nextNode();)if(7===d.nodeType){var a;if(a="start"===d.target)a=d,a="function"===typeof a.getAttribute?a.getAttribute("name"):(a=(a.data||a.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?a[1]:null,a=a===c;if(a){c=d;break a}}else{if(a=8===d.nodeType)a=d.data,"string"!==typeof a||63!==a.charCodeAt(0)?a=!1:(a=a.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),a=null!=a&&"start"===a[1]&&a[2]===c);if(a){c=d;break a}}c=null}return c};$RM=new Map;\n$RR=function(c,f,d){function a(t){this._p=null;t()}for(var u=new Map,v=document,n,e,k=v.querySelectorAll("link[data-precedence],style[data-precedence]"),w=[],p=0;e=k[p++];)"not all"===e.getAttribute("media")?w.push(e):("LINK"===e.tagName&&$RM.set(e.getAttribute("href"),e),u.set(e.dataset.precedence,n=e));k=0;e=[];var q,b;for(p=!0;;){if(p){var l=d[k++];if(!l){p=!1;k=0;continue}var g=!1,r=0;var h=l[r++];if(b=$RM.get(h)){var m=b._p;g=!0}else{b=v.createElement("link");b.href=h;b.rel=\n"stylesheet";for(b.dataset.precedence=q=l[r++];m=l[r++];)b.setAttribute(m,l[r++]);m=b._p=new Promise(function(t,y){b.onload=a.bind(b,t);b.onerror=a.bind(b,y)});$RM.set(h,b)}h=b.getAttribute("media");!m||h&&!matchMedia(h).matches||e.push(m);if(g)continue}else{b=w[k++];if(!b)break;q=b.getAttribute("data-precedence");b.removeAttribute("media")}g=u.get(q)||n;g===n&&(n=b);u.set(q,b);g?g.parentNode.insertBefore(b,g.nextSibling):(g=v.head,g.insertBefore(b,g.firstChild))}if(d=x(c))d.previousSibling.data=\n"$~";Promise.all(e).then($RC.bind(null,c,f),$RX.bind(null,c,"CSS failed to load"))};';
export const completeSegment =
  '$RS=function(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};';
export const formReplaying =
  'addEventListener("submit",function(a){if(!a.defaultPrevented){var b=a.target,d=a.submitter,c=b.action,e=d;if(d){var f=d.getAttribute("formAction");null!=f&&(c=f,e=null)}"javascript:throw new Error(\'React form unexpectedly submitted.\')"===c&&(a.preventDefault(),a=new FormData(b,e),c=b.ownerDocument||b,(c.$$reactFormReplay=c.$$reactFormReplay||[]).push(b,d,a))}});';
