// This is a generated file. The source files are in react-dom-bindings/src/server/fizz-instruction-set.
// The build script is at scripts/rollup/generate-inline-fizz-runtime.js.
// Run `yarn generate-inline-fizz-runtime` to generate.
export const markShellTime =
  'requestAnimationFrame(function(){$RT=performance.now()});';
export const clientRenderBoundary =
  '$RX=function(d,e,f,g,h){var c,b=document.getElementById(d);if(!b)a:{b=document;for(b=b.createTreeWalker(b.documentElement||b,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);c=b.nextNode();)if(7===c.nodeType){var a;if(a="start"===c.target)a=c,a="function"===typeof a.getAttribute?a.getAttribute("name"):(a=(a.data||a.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?a[1]:null,a=a===d;if(a){b=c;break a}}else{if(a=8===c.nodeType)a=c.data,"string"!==typeof a||63!==a.charCodeAt(0)?a=!1:(a=a.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),a=null!=a&&"start"===a[1]&&a[2]===d);if(a){b=c;break a}}b=null}if(c=b)b=c.previousSibling,b.data="$!",a=c,1!==c.nodeType&&(a=b.ownerDocument.createElement("template"),a.id=d,b.parentNode.insertBefore(a,c)),d=a.dataset,null!=e&&(d.dgst=e),f&&(d.msg=f),g&&(d.stck=g),h&&(d.cstck=h),b._reactRetry&&b._reactRetry()};';
export const completeBoundary =
  '$RB=[];$RV=function(c){$RT=performance.now();for(var d=0;d<c.length;d+=2){var b=c[d],e=c[d+1];null!==e.parentNode&&e.parentNode.removeChild(e);var a=b.parentNode;if(a){var g=b.previousSibling,h=0;do{if(b&&8===b.nodeType){var f=b.data;if("/$"===f||"/&"===f)if(0===h)break;else h--;else"$"!==f&&"$?"!==f&&"$~"!==f&&"$!"!==f&&"&"!==f||h++}f=b.nextSibling;a.removeChild(b);b=f}while(b);for(;e.firstChild;)a.insertBefore(e.firstChild,b);g.data="$";g._reactRetry&&requestAnimationFrame(g._reactRetry)}}c.length=0};\n$RC=function(c,d){if(d=document.getElementById(d)){var b=document.getElementById(c);if(b)c=b;else a:{b=document;b=b.createTreeWalker(b.documentElement||b,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);for(var e;e=b.nextNode();)if(7===e.nodeType){var a;if(a="start"===e.target)a=e,a="function"===typeof a.getAttribute?a.getAttribute("name"):(a=(a.data||a.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?a[1]:null,a=a===c;if(a){c=e;break a}}else{if(a=8===e.nodeType)a=e.data,\n"string"!==typeof a||63!==a.charCodeAt(0)?a=!1:(a=a.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),a=null!=a&&"start"===a[1]&&a[2]===c);if(a){c=e;break a}}c=null}c?(c.previousSibling.data="$~",$RB.push(c,d),2===$RB.length&&("number"!==typeof $RT?requestAnimationFrame($RV.bind(null,$RB)):(d=performance.now(),setTimeout($RV.bind(null,$RB),2300>d&&2E3<d?2300-d:$RT+300-d)))):d.parentNode.removeChild(d)}};';
export const completeBoundaryDeclarative =
  'function f(e,b){var c=document;c=c.createTreeWalker(c.documentElement||c,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);for(var d;d=c.nextNode();)if(7===d.nodeType){var a;if(a=d.target===e)a=d,a="function"===typeof a.getAttribute?a.getAttribute("name"):(a=(a.data||a.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?a[1]:null,a=a===b;if(a)return d}else{if(a=8===d.nodeType)a=d.data,"string"!==typeof a||63!==a.charCodeAt(0)?a=!1:(a=a.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),a=null!=a&&a[1]===e&&a[2]===b);if(a)return d}return null};$RP=function(e){a:{var b=document.querySelectorAll("template");for(var c=0;c<b.length;c++)if(b[c].getAttribute("for")===e){b=b[c];break a}b=null}if(null!==b&&null!==b.parentNode)if(c=f("start",e),null===c||null===c.parentNode)b.parentNode.removeChild(b);else{for(var d=c.parentNode,a=c.nextSibling;a;){var g=a.nextSibling,h=7===a.nodeType?"end"===a.target:8===a.nodeType?"string"===typeof a.data&&/^\\?end\\b/.test(a.data):!1;d.removeChild(a);if(h)break;a=g}for(a=b.content;a.firstChild;)d.insertBefore(a.firstChild,\nc);d.removeChild(c);null!==b.parentNode&&b.parentNode.removeChild(b)}if(e=f("marker",e))for(b=e.previousSibling,c=0;b;){if(8===b.nodeType)if(d=b.data,"/$"===d||"/&"===d)c++;else if("$"===d||"$?"===d||"$~"===d||"$!"===d||"&"===d){if(0===c){b.data="$";e.parentNode.removeChild(e);b._reactRetry&&requestAnimationFrame(b._reactRetry);break}c--}b=b.previousSibling}};';
export const completeBoundaryUpgradeToViewTransitions =
  '$RV=function(B,g){function h(a,c){var e=a.getAttribute(c);e&&(c=a.style,l.push(a,c.viewTransitionName,c.viewTransitionClass),"auto"!==e&&(c.viewTransitionClass=e),(a=a.getAttribute("vt-name"))||(a="_T_"+N++ +"_"),a=CSS.escape(a)!==a?"r-"+btoa(a).replace(/=/g,""):a,c.viewTransitionName=a,C=!0)}var C=!1,N=0,l=[];try{var f=document.__reactViewTransition;if(f){f.finished.finally($RV.bind(null,g));return}var m=new Map;for(f=1;f<g.length;f+=2)for(var k=g[f].querySelectorAll("[vt-share]"),d=0;d<k.length;d++){var b=k[d];m.set(b.getAttribute("vt-name"),b)}var u=[];for(k=0;k<g.length;k+=2){var D=g[k],x=D.parentNode;if(x){var v=x.getBoundingClientRect();if(v.left||v.top||v.width||v.height){b=D;for(f=0;b;){if(8===b.nodeType){var t=b.data;if("/$"===t)if(0===f)break;else f--;else"$"!==t&&"$?"!==t&&"$~"!==t&&"$!"!==t||f++}else if(1===b.nodeType){d=b;var E=d.getAttribute("vt-name"),y=m.get(E);h(d,y?"vt-share":"vt-exit");y&&(h(y,"vt-share"),m.set(E,null));for(var F=d.querySelectorAll("[vt-share]"),\nz=0;z<F.length;z++){var G=F[z],H=G.getAttribute("vt-name"),I=m.get(H);I&&(h(G,"vt-share"),h(I,"vt-share"),m.set(H,null))}var J=d.querySelectorAll("[vt-parent-exit]");for(d=0;d<J.length;d++)h(J[d],"vt-parent-exit")}b=b.nextSibling}for(var K=g[k+1],n=K.firstElementChild;n;){null!==m.get(n.getAttribute("vt-name"))&&h(n,"vt-enter");var L=n.querySelectorAll("[vt-parent-enter]");for(b=0;b<L.length;b++)h(L[b],"vt-parent-enter");n=n.nextElementSibling}b=x;do for(var p=b.firstElementChild;p;){var M=p.getAttribute("vt-update");\nM&&"none"!==M&&!l.includes(p)&&h(p,"vt-update");p=p.nextElementSibling}while((b=b.parentNode)&&1===b.nodeType&&"none"!==b.getAttribute("vt-update"));u.push.apply(u,K.querySelectorAll(\'img[src]:not([loading="lazy"])\'))}}}if(C){var A=document.__reactViewTransition=document.startViewTransition({update:function(){B(g);for(var a=[document.documentElement.clientHeight,document.fonts.ready],c={},e=0;e<u.length;c={g:c.g},e++)if(c.g=u[e],!c.g.complete){var q=c.g.getBoundingClientRect();0<q.bottom&&0<q.right&&\nq.top<window.innerHeight&&q.left<window.innerWidth&&(q=new Promise(function(w){return function(r){w.g.addEventListener("load",r);w.g.addEventListener("error",r)}}(c)),a.push(q))}return Promise.race([Promise.all(a),new Promise(function(w){var r=performance.now();setTimeout(w,2300>r&&2E3<r?2300-r:500)})])},types:[]});A.ready.finally(function(){for(var a=l.length-3;0<=a;a-=3){var c=l[a],e=c.style;e.viewTransitionName=l[a+1];e.viewTransitionClass=l[a+1];""===c.getAttribute("style")&&c.removeAttribute("style")}});\nA.finished.finally(function(){document.__reactViewTransition===A&&(document.__reactViewTransition=null)});$RB=[];return}}catch(a){}B(g)}.bind(null,$RV);';
export const completeBoundaryWithStyles =
  'function x(c){var f=document.getElementById(c);if(f)c=f;else a:{f=document;f=f.createTreeWalker(f.documentElement||f,NodeFilter.SHOW_PROCESSING_INSTRUCTION|NodeFilter.SHOW_COMMENT);for(var d;d=f.nextNode();)if(7===d.nodeType){var a;if(a="start"===d.target)a=d,a="function"===typeof a.getAttribute?a.getAttribute("name"):(a=(a.data||a.nodeValue||"").match(/(?:^|\\s)name=["\']([^"\']+)["\']/))?a[1]:null,a=a===c;if(a){c=d;break a}}else{if(a=8===d.nodeType)a=d.data,"string"!==typeof a||63!==a.charCodeAt(0)?a=!1:(a=a.match(/^\\?([^\\s]+)\\s+name=["\']([^"\']+)["\']/),a=null!=a&&"start"===a[1]&&a[2]===c);if(a){c=d;break a}}c=null}return c};$RM=new Map;\n$RR=function(c,f,d){function a(t){this._p=null;t()}for(var u=new Map,v=document,n,e,k=v.querySelectorAll("link[data-precedence],style[data-precedence]"),w=[],p=0;e=k[p++];)"not all"===e.getAttribute("media")?w.push(e):("LINK"===e.tagName&&$RM.set(e.getAttribute("href"),e),u.set(e.dataset.precedence,n=e));k=0;e=[];var q,b;for(p=!0;;){if(p){var l=d[k++];if(!l){p=!1;k=0;continue}var g=!1,r=0;var h=l[r++];if(b=$RM.get(h)){var m=b._p;g=!0}else{b=v.createElement("link");b.href=h;b.rel=\n"stylesheet";for(b.dataset.precedence=q=l[r++];m=l[r++];)b.setAttribute(m,l[r++]);m=b._p=new Promise(function(t,y){b.onload=a.bind(b,t);b.onerror=a.bind(b,y)});$RM.set(h,b)}h=b.getAttribute("media");!m||h&&!matchMedia(h).matches||e.push(m);if(g)continue}else{b=w[k++];if(!b)break;q=b.getAttribute("data-precedence");b.removeAttribute("media")}g=u.get(q)||n;g===n&&(n=b);u.set(q,b);g?g.parentNode.insertBefore(b,g.nextSibling):(g=v.head,g.insertBefore(b,g.firstChild))}if(d=x(c))d.previousSibling.data=\n"$~";Promise.all(e).then($RC.bind(null,c,f),$RX.bind(null,c,"CSS failed to load"))};';
export const completeSegment =
  '$RS=function(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};';
export const formReplaying =
  'addEventListener("submit",function(a){if(!a.defaultPrevented){var b=a.target,d=a.submitter,c=b.action,e=d;if(d){var f=d.getAttribute("formAction");null!=f&&(c=f,e=null)}"javascript:throw new Error(\'React form unexpectedly submitted.\')"===c&&(a.preventDefault(),a=new FormData(b,e),c=b.ownerDocument||b,(c.$$reactFormReplay=c.$$reactFormReplay||[]).push(b,d,a))}});';
